name: church_tool
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.2
  hooks_riverpod: ^2.5.1
  lpinyin: ^2.0.3
  meta_seo: ^3.0.9
  posthog_flutter: ^4.5.0
  shadcn_ui: ^0.4.7
  shared_preferences: ^2.2.3
  universal_io: ^2.2.2
  url_launcher: ^6.2.6
  xml: ^6.5.0

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter

  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
